version: '3.9'

services: 
  mysql_typers:
    image: mysql/mysql-server:latest
    ports: 
      - "3320:3306"
    volumes: 
      - db_volume_typers:/var/lib/mysql
      - ../db/typers.sql:/docker-entrypoint-initdb.d/typers.sql:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_HOST: localhost
      MYSQL_DATABASE: "typers"
      MYSQL_USER: "root"
    container_name: db_typers
  
  mongo_contactos:
    image: mongo:4.4.4
    ports: 
      - "33021:27017"
    hostname: mongo_contactos
    restart: unless-stopped
    volumes: 
      - db_volume_contactos:/data/db
      - ../db/contactos.js:/docker-entrypoint-initdb.d/contactos.js:ro
    command: mongod --auth
    environment: 
      MONGO_INITDB_DATABASE: contactos
      MONGO_INITDB_ROOT_USERNAME: adminContactos
      MONGO_INITDB_ROOT_PASSWORD: proyecto2021
    container_name: db_contactos
  
  mysql_mensajes:
    image: mysql/mysql-server:latest
    ports: 
      - "3322:3306"
    volumes: 
      - db_volume_mensajes:/var/lib/mysql
      - ../db/mensajes.sql:/docker-entrypoint-initdb.d/mensajes.sql:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_HOST: localhost
      MYSQL_DATABASE: "mensajes"
      MYSQL_USER: "root"
    container_name: db_mensajes
  
  mysql_multimedia:
    image: mysql/mysql-server:latest
    ports: 
      - "3323:3306"
    volumes: 
      - db_volume_multimedia:/var/lib/mysql
      - ../db/multimedia.sql:/docker-entrypoint-initdb.d/multimedia.sql:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_0900_ai_ci']
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_HOST: localhost
      MYSQL_DATABASE: "multimedia"
      MYSQL_USER: "root"
    container_name: db_multimedia

  ms_typers:
    image: ms_typers
    depends_on: 
        - "mysql_typers"
    ports:
        - "3324:80"
    build: https://github.com/BaezCrdrmUV/proyecto-equipoa.git#MSTypers
    environment: 
        DB_CONNECTION_STRING: "server=mysql_typers;user=adminTypers;password=proyecto2021;database=Typers"

  ms_multimedia:
    image: ms_multimedia
    depends_on: 
        - "mysql_multimedia"
    ports:
        - "3325:80"
    build: https://github.com/BaezCrdrmUV/proyecto-equipoa.git#MSMultimedia
    environment: 
        DB_CONNECTION_STRING: "server=mysql_multimedia;user=adminMultimedia;password=proyecto2021;database=Multimedias"

  ms_mensajes:
    image: ms_mensajes
    depends_on: 
      - "mysql_mensajes"
    ports:
      - "3326:80"
    build: https://github.com/BaezCrdrmUV/proyecto-equipoa.git#MSMensajes
    environment: 
      DB_CONNECTION_STRING: "server=mysql_mensajes;user=adminMensajes;password=proyecto2021;database=Mensajes"

  ms_contactos:
    image: ms_contactos
    depends_on: 
      - "mongo_contactos"
    ports: 
      - "3327:5000"
    build: https://github.com/BaezCrdrmUV/proyecto-equipoa.git#MSContactos
    environment: 
      FLASK_ENV: production
      FLASK_APP: src/app.py
      FLASK_RUN_HOST: 0.0.0.0
      MONGO_URI: mongodb://adminContactos:proyecto2021@mongo_contactos/contactos

  apigateway:
    image: apigateway
    ports: 
      - "4000:4000"
    build: https://github.com/BaezCrdrmUV/proyecto-equipoa.git#apigateway
    environment:
      URL_MS_TYPERS: http://ms_typers
      URL_MS_MULTIMEDIA: http://ms_multimedia
      URL_AMISTOSA: http://localhost:3325
      URL_MS_MENSAJES: http://ms_mensajes
      URL_MS_CONTACTOS: http://ms_contactos:5000
    container_name: apigateway

  typeme_web:
    image: typeme_web
    ports: 
      - "5000:80"
    build: https://github.com/SammyGCh/TypeMe.git#TypeMeWeb
    environment: 
      URL_API: "http://apigateway:4000"

volumes:
  db_volume_typers:
  db_volume_contactos:
  db_volume_mensajes:
  db_volume_multimedia:
